CREATE TABLE tb_custumer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zip_code VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_tb_custumer PRIMARY KEY (id)
);

ALTER TABLE tb_custumer ADD CONSTRAINT uc_tb_custumer_cpf UNIQUE (cpf);

ALTER TABLE tb_custumer ADD CONSTRAINT uc_tb_custumer_email UNIQUE (email);